onCheckpointEntered(player, checkpoint);
onCheckpointExited(player, checkpoint);
onObjectShot(object, player, weapon);
onObjectBump(object, player);
onPickupClaimPicked(player, pickup);
onPickupPickedUp(player, pickup);
onPickupRespawn(pickup);
onPlayerJoin(player);
onPlayerPart(player, reason);
onPlayerRequestClass(player, classID, team, skin);
onPlayerRequestSpawn(player);
onPlayerSpawn(player);
onPlayerDeath(player, reason);
onPlayerKill(killer, player, reason, bodypart);
onPlayerTeamKill(killer, player, reason, bodypart);
onPlayerChat(player, message);
onPlayerCommand(player, command, arguments);
onPlayerPM(player, playerTo, message);
onPlayerBeginTyping(player);
onPlayerEndTyping(player);
onLoginAttempt(playerName, password, ipAddress);
onPlayerMove(player, lastX, lastY, lastZ, newX, newY, newZ);
onPlayerHealthChange(player, lastHP, newHP);
onPlayerArmourChange(player, lastArmour, newArmour);
onPlayerWeaponChange(player, oldWep, newWep);
onKeyDown(player, bindID);
onKeyUp(player, bindID);
onPlayerAwayChange(player, newStatus);
onPlayerSpectate(player, target);
onPlayerCrashDump(player, crashReport);
onPlayerNameChange(player, oldName, newName);
onPlayerActionChange(player, oldAction, newAction);
onPlayerStateChange(player, oldState, newState);
onPlayerOnFireChange(player, isOnFireNow);
onPlayerCrouchChange(player, isCrouchingNow);
onPlayerGameKeysChange(player, oldKeys, newKeys);
onPlayerModuleList (player, string);
onServerStart();
onServerStop();
onScriptLoad();
onScriptUnload();
onClientScriptData(player);
onSphereEntered(player, sphere);
onSphereExited(player, sphere);
onPlayerEnteringVehicle(player, vehicle, door);
onPlayerEnterVehicle(player, vehicle, door);
onPlayerExitVehicle(player, vehicle);
onVehicleExplode(vehicle);
onVehicleRespawn(vehicle);
onVehicleHealthChange(vehicle, oldHP, newHP);
onVehicleMove(vehicle, lastX, lastY, lastZ, newX, newY, newZ);